# Generated by Django 2.0.5 on 2018-05-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmenu',
            name='position',
        ),
    ]
