# Generated by Django 2.0.5 on 2018-05-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_topmenu_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=300)),
                ('categoryid', models.CharField(max_length=20)),
                ('brandname', models.CharField(max_length=20)),
                ('img1', models.CharField(max_length=300)),
                ('childcid1', models.CharField(max_length=50)),
                ('productid1', models.CharField(max_length=50)),
                ('longname1', models.CharField(max_length=200)),
                ('price1', models.CharField(max_length=20)),
                ('marketprice1', models.CharField(max_length=20)),
                ('img2', models.CharField(max_length=300)),
                ('childcid2', models.CharField(max_length=50)),
                ('productid2', models.CharField(max_length=50)),
                ('longname2', models.CharField(max_length=200)),
                ('price2', models.CharField(max_length=20)),
                ('marketprice2', models.CharField(max_length=20)),
                ('img3', models.CharField(max_length=300)),
                ('childcid3', models.CharField(max_length=50)),
                ('productid3', models.CharField(max_length=50)),
                ('longname3', models.CharField(max_length=200)),
                ('price3', models.CharField(max_length=20)),
                ('marketprice3', models.CharField(max_length=30)),
            ],
        ),
    ]
