# Generated by Django 2.0.5 on 2018-05-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_showstore'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='showstore',
            table='axf_mainshow',
        ),
    ]
