# Generated by Django 2.0.5 on 2018-05-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20180521_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=300)),
                ('childcid', models.CharField(max_length=50)),
                ('productid', models.CharField(max_length=50)),
                ('longname', models.CharField(max_length=200)),
                ('price1', models.CharField(max_length=20)),
                ('marketprice', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'axf_brandproduct',
            },
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='childcid1',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='childcid2',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='childcid3',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='longname1',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='longname2',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='longname3',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='marketprice1',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='marketprice2',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='marketprice3',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='productid1',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='productid2',
        ),
        migrations.RemoveField(
            model_name='showstore',
            name='productid3',
        ),
    ]
