# Generated by Django 2.0.5 on 2018-05-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20180522_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandproduct',
            old_name='price1',
            new_name='price',
        ),
    ]
