# Generated by Django 2.0.5 on 2018-05-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20180522_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandproduct',
            name='showstore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ShowStore'),
        ),
    ]
