# Generated by Django 2.0.5 on 2018-05-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20180525_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='isSelected',
            field=models.BooleanField(default=False),
        ),
    ]
